# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="SULLR"


inherit perl-module

DESCRIPTION="Help Net::* (SMTP,..), LWP... deal with IPv6"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/IO-Socket-INET6
	dev-lang/perl"
