# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="PEVANS"


inherit perl-module

DESCRIPTION="C<IO::Socket::IP> - A drop-in replacement for C<IO::Socket::INET> supporting both IPv4 and IPv6"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Socket-GetAddrInfo-0.210.0
	dev-lang/perl"
