#!/bin/sh

# FLEXlm init script
# Designed to work as an umbrella daemon for multiple vendor licenses
#
# Created by Brian Morris (bmorris {at}  cyberarmor zDOTz net), 08/08/2011
#
# Change the variables below to fit your environment

FLEXLM_USER="scl"
FLEXLM_GROUP="scl"
FLEXLM_BASEDIR="/home/scl/SCL_11.4"
FLEXLM_LICENSEDIR="${FLEXLM_BASEDIR}/../keys/"
FLEXLM_BINDIR="${FLEXLM_BASEDIR}/amd64/bin"
FLEXLM_BIN="${FLEXLM_BINDIR}/lmgrd"
FLEXLM_UTIL="${FLEXLM_BINDIR}/lmutil"
FLEXLM_LOGDIR="${FLEXLM_BASEDIR}/admin/logs"

PATH="${PATH}:${FLEXLM_BINDIR}"
SUDO_BIN="sudo -u ${FLEXLM_USER} -g ${FLEXLM_GROUP}"
########## DO NOT CHANGE ANYTHING BELOW THIS LINE ##########

# Check for the existence of the FLEXLM daemon
test -x ${FLEXLM_BIN} || { echo "${FLEXLM_BIN} is not installed"; 
	if [ "$1" = "stop" ]; then exit 0;
	else exit 5; fi; }

# Check for the existence of the FLEXLM utility
test -x ${FLEXLM_UTIL} || { echo "${FLEXLM_UTIL} is not installed";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

# Check license files for read access
FLEXLM_LICENSE=`find ${FLEXLM_LICENSEDIR} -name "*license.lic"`
for file in ${FLEXLM_LICENSE}
do
    test -r ${file} || { echo "${file} not readable. Please correct its permissions.";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }
done


function start {
        echo -n "\n"
        for file in ${FLEXLM_LICENSE}
        do
                SERVICE=`basename ${file} | awk -F. '{print $1}'`
                echo "Starting ${SERVICE} license server"
                ${SUDO_BIN} ${FLEXLM_BIN} -c ${file} -L ${FLEXLM_LOGDIR}/${SERVICE}.flexlm.log
        done
        echo -n "\n"
}

function stop {
        for file in ${FLEXLM_LICENSE}
        do
                SERVICE=`basename ${file} | awk -F. '{print $1}'`
                echo "\nStopping ${SERVICE} license server"
                ${SUDO_BIN} ${FLEXLM_UTIL} lmdown -all -c ${file}
		echo -n "\n"
        done
        echo -n "\nWaiting for all license ports to close..."
        # The CST license daemon takes around 50 seconds to spin down,
	# so I set this at 60 seconds.
        for i in `seq 1 60`;
        do
                sleep 1
                echo -n "."
        done
        echo "\n"
}

function reload {
	for file in ${FLEXLM_LICENSE}
	do
		SERVICE=`basename ${file} | awk -F. '{print $1}'`
		echo "\nRereading ${SERVICE}"
		${SUDO_BIN} ${FLEXLM_UTIL} lmreread -c ${file}
		echo -n "\n"
	done
}


case "$1" in
	start)
		start
	;;

	stop)
		stop
        ;;
	
	restart)
		stop
		start
	;;

	reload)
		reload
	;;

	*)
	echo "\nUsage: /etc/init.d/flexlm {start|stop|restart|reload}\n"
	;;

esac
