#! /bin/bash
for i in `ls /dev/zram? | cut -d "/" -f 3`; do
        ODS=`cat /sys/block/$i/orig_data_size`
        MEM=`cat /sys/block/$i/mem_used_total`
        CDS=`cat /sys/block/$i/compr_data_size`
        echo Compression ratio of $i: `echo "scale=3; $ODS/$CDS;"|bc -l` net, `echo "scale=3; $ODS/$MEM;"|bc -l` gross.
done
