#!/bin/bash

devices_num() {
	DEVICES_NUMBER=$( grep -oi "zram.num_devices=[[:digit:]]" /proc/cmdline | cut -d '=' -f 2 )
	if [[ "x${DEVICES_NUMBER}x" == 'xx' ]]; then
		if ( grep -qi "portage_tmp_zram" /proc/cmdline); then
			DEVICES_NUMBER=$((${DEVICES_NUMBER}+1))
		fi
		if ( grep -qi "swap_zram" /proc/cmdline); then
			DEVICES_NUMBER=$((${DEVICES_NUMBER}+${CPUS}))
		fi
	fi

	echo ${DEVICES_NUMBER}
}

portage_tmp_zram_dev_name() {
        if ( grep -qi "portage_tmp_zram" /proc/cmdline ) && ( grep -qi "swap_zram" /proc/cmdline ); then
		ZRAM_DEV="zram"${CPUS}
	else
		if ( grep -qi "portage_tmp_zram" /proc/cmdline ); then
			ZRAM_DEV="zram0"
		fi
	fi
	echo ${ZRAM_DEV}
}

start() {
	CPUS=`grep -Ec "^processor" /proc/cpuinfo`
	DEVICES=$(devices_num)
        RAM=$(grep MemTotal /proc/meminfo | awk ' { print $2 } ')
	STREAMS=1
	ALG=lzo
	SWAP_FACTOR=50
	PORTAGE_TMP_FACTOR=50
	[ -f /etc/conf.d/zram ] && source /etc/conf.d/zram || true

	modprobe zram num_devices=${DEVICES}

	PORTAGE_TMP_ZRAM_DEV=$(portage_tmp_zram_dev_name)
        if ( grep -qi "portage_tmp_zram" /proc/cmdline); then
		size=$(($RAM*$PORTAGE_TMP_FACTOR/100*1024))
		#inodes="-N $((262144))"
		echo "Setting algorithm and streams number for ZRAM /tmp/portage_zram"
		echo $STREAMS > /sys/block/${PORTAGE_TMP_ZRAM_DEV}/max_comp_streams
		echo $ALG > /sys/block/${PORTAGE_TMP_ZRAM_DEV}/comp_algorithm
                echo "Creating ZRAM /tmp/portage_zram and mounting"
                echo $size > /sys/block/${PORTAGE_TMP_ZRAM_DEV}/disksize
                mkfs.ext4 -q -O dir_nlink,extent,extra_isize,flex_bg,^has_journal,uninit_bg -m0 -b 4096 $inodes -L ${PORTAGE_TMP_ZRAM_DEV} /dev/${PORTAGE_TMP_ZRAM_DEV}
                mount -o barrier=0,commit=240,noatime,nodev /dev/${PORTAGE_TMP_ZRAM_DEV} /tmp/portage_zram
                chown portage:portage /tmp/portage_zram
                chmod 0775 /tmp/portage_zram
		if [ -d /tmp/portage/.distcc ]; then
			mkdir /tmp/portage_zram/.distcc
			mount -o bind /tmp/portage/.distcc /tmp/portage_zram/.distcc
		fi
        fi

        if ( grep -qi "swap_zram" /proc/cmdline); then
		mem_by_cpu=$(($RAM/$CPUS*$SWAP_FACTOR/100*1024))
		echo "Activating $CPUS zram swap device(s), using $mem_by_cpu per cpu."

		#modprobe zram num_devices=${CPUS}

	        for (( i=0; i<$CPUS; i++ )); do
			echo $STREAMS > /sys/block/zram$i/max_comp_streams
			echo $ALG > /sys/block/zram$i/comp_algorithm
	                echo $mem_by_cpu > /sys/block/zram$i/disksize
	                mkswap /dev/zram$i
	                swapon -d -p 10 /dev/zram$i
	        done
	fi
}

stop() {
	if ( grep -qi "swap_zram" /proc/cmdline ); then
		echo "Disactivating Swap ZRAM"
		CPUS=`grep -Ec "^processor" /proc/cpuinfo`
			for (( i=0; i<$CPUS; i++ )); do
				grep -q "/dev/zram$i" /proc/swaps && swapoff /dev/zram$i
				grep -q "/dev/zram$i" /proc/swaps && echo 1 > /sys/block/zram$i/reset
                        done
		sleep 1
	fi
        if ( grep -qi "portage_tmp_zram" /proc/cmdline ); then
                echo "Unmounting ZRAM"
		DEV=$(portage_tmp_zram_dev_name)
                umount /dev/${DEV}
		echo 1 > /sys/block/${DEV}/reset
        fi
	rmmod zram
}

OPERATION="$1"

if [ "x${OPERATION}x" == "xstartx" ]; then
        start;
else
        if [ "x${OPERATION}x" == "xstopx" ]; then
                stop;
        else
                echo "No operation specified"
                exit 1
        fi
fi

